
INSERT INTO public.translations (key, locale, value) VALUES
-- Navbar EN
('nav.about','en','About'),('nav.howItWorks','en','How It Works'),('nav.features','en','Features'),('nav.security','en','Security'),('nav.boostPlans','en','Boost Plans'),('nav.ecosystem','en','Ecosystem'),('nav.faq','en','FAQ'),('nav.getStarted','en','Get Started'),
-- Hero EN
('hero.live','en','Live Mining — 3,310+ Active Miners'),('hero.badge','en','Built on DannyChain × Bitget Wallet'),('hero.title1','en','Mine'),('hero.title2','en','HMOOB'),('hero.title3','en','Earn Every Day.'),('hero.desc','en','Connect via Bitget Wallet, boost your hash rate, and mine HMOOB tokens — no hardware needed. Earn'),('hero.roi','en','365% ROI'),('hero.descEnd','en','over 365 days on the DannyChain ecosystem.'),('hero.startMining','en','Start Mining'),('hero.downloadWallet','en','Download Bitget Wallet'),('hero.annualRoi','en','365% Annual ROI'),('hero.noHardware','en','No Hardware Required'),('hero.selfCustodial','en','Self-Custodial Wallet'),
-- Trust EN
('trust.poweredBy','en','Powered By & Integrated With'),
-- About EN
('about.label','en','About HMOOB Mining'),('about.title1','en','The'),('about.title2','en','Hmong Community''s'),('about.titleEnd','en','Own Crypto Token'),('about.p1','en','HMOOB Mining is a cloud-based mining platform built on the DannyChain Layer 2 blockchain. Users connect through the'),('about.bitget','en','Bitget Wallet'),('about.p1End','en','app — a trusted Web3 wallet with 80M+ users — to mine HMOOB tokens by purchasing boost plans and earning daily rewards, all without any physical hardware.'),('about.p2','en','Part of a growing ecosystem that includes DannyChain (Layer 2 blockchain), DanDEX (decentralized exchange), DanMarket (decentralized marketplace), and DanScan (blockchain explorer) — HMOOB Mining represents the Hmong community''s entry into Web3 with a platform designed for accessibility and simplicity.'),
-- AppPreview EN
('appPreview.label','en','Mobile-First Platform'),('appPreview.title1','en','Mine Anywhere,'),('appPreview.title2','en','Anytime'),('appPreview.desc','en','HMOOB Mining works seamlessly through the'),('appPreview.descEnd','en','app — a trusted Web3 wallet with 80M+ users worldwide. Simply open hmoob.io inside the wallet''s DApp browser to access all features.'),('appPreview.desc2','en','Bitget Wallet provides self-custodial security, multi-chain support, and a built-in DApp browser — making it the perfect gateway to HMOOB Mining and the DannyChain ecosystem.'),('appPreview.openApp','en','Open HMOOB Mining'),('appPreview.getWallet','en','Get Bitget Wallet'),('appPreview.hmoobDesc','en','Cloud mining — boost hash rate, earn daily HMOOB rewards'),('appPreview.dandexDesc','en','Decentralized exchange — swap tokens, provide liquidity, live charts'),('appPreview.danscanDesc','en','Blockchain explorer — track transactions, blocks, wallets & gas'),('appPreview.compatibleWallets','en','Compatible Wallets'),
-- HowItWorks EN
('howItWorks.label','en','How It Works'),('howItWorks.title1','en','Four Steps to'),('howItWorks.title2','en','Mine HMOOB'),('howItWorks.cta','en','Get it on Google Play'),('howItWorks.wallet','en','Bitget Wallet'),
-- Features EN
('features.label','en','Platform Features'),('features.title1','en','Everything in'),('features.title2','en','One Platform'),('features.desc','en','Mine, earn, swap, and grow your HMOOB portfolio'),
-- Security EN
('security.label','en','Security & Trust'),('security.title1','en','Your Assets,'),('security.title2','en','Your Control'),('security.desc','en','Built with industry-leading security practices — because trust is earned, not assumed'),('security.verify','en','Verify on DanScan Explorer ↗'),
-- Boost EN
('boost.label','en','Mining Boosts'),('boost.title1','en','Boost Your'),('boost.title2','en','Mining Power'),('boost.desc','en','Increase your hash rate and earn more HMOOB with our boost plans'),('boost.recommended','en','Recommended'),('boost.suffix','en','Boost'),('boost.hashRate','en','Hash Rate'),('boost.miningPower','en','Mining Power'),('boost.totalReturn','en','Total Return'),('boost.duration','en','Duration'),('boost.days','en','365 days'),('boost.getBoost','en','Get Boost'),
-- Ecosystem EN
('ecosystem.label','en','Ecosystem'),('ecosystem.title1','en','The'),('ecosystem.title2','en','DannyChain'),('ecosystem.titleEnd','en','Ecosystem'),('ecosystem.desc','en','HMOOB Mining is part of a complete blockchain ecosystem — from Layer 2 infrastructure to decentralized trading'),
-- EcosystemFlow EN
('flow.label','en','How It All Connects'),('flow.title1','en','One Ecosystem,'),('flow.title2','en','Three Platforms'),('flow.titleEnd','en',''),('flow.desc','en','Download a compatible wallet, connect to DannyChain, and access the full ecosystem — mining, trading, and exploring all in one place'),('flow.step1Title','en','Get a Wallet'),('flow.step1Desc','en','Download any compatible Web3 wallet with DApp browser support'),('flow.step2Title','en','Connect to DannyChain'),('flow.step2Desc','en','Open any platform URL inside the wallet''s built-in DApp browser'),('flow.step3Title','en','Access the Ecosystem'),('flow.step3Desc','en','Mine HMOOB, trade on DanDEX, or explore transactions on DanScan'),('flow.miningDesc','en','Cloud mining — earn daily HMOOB rewards with up to 365% ROI'),('flow.dexDesc','en','Decentralized exchange — swap tokens and provide liquidity'),('flow.scanDesc','en','Blockchain explorer — track transactions, blocks, and wallets'),
-- Vision EN
('vision.label','en','Our Vision'),('vision.quote','en','"HMOOB Mining is more than a platform — it''s our community''s gateway into the decentralized future. Built on DannyChain, we''re creating a complete ecosystem where the Hmong community and all users can mine, earn, swap, and grow together."'),('vision.team','en','The HMOOB Team'),('vision.role','en','Founders & Builders'),('vision.roadmapTitle1','en','Our'),('vision.roadmapTitle2','en','Roadmap'),('vision.now','en','NOW'),
-- Video EN
('video.label','en','Watch'),('video.title1','en','See How'),('video.title2','en','Hmoob.io'),('video.titleEnd','en','Works'),('video.desc','en','Learn about our vision and cloud mining system that makes earning crypto simple for everyone'),
-- Testimonials EN
('testimonials.label','en','Community'),('testimonials.title1','en','What Our'),('testimonials.title2','en','Miners Say'),('testimonials.desc','en','Real feedback from verified community members'),('testimonials.verified','en','Verified'),('testimonials.hashRate','en','Hash Rate'),('testimonials.boost','en','Boost'),
-- FAQ EN
('faq.label','en','FAQ'),('faq.title1','en','Frequently Asked'),('faq.title2','en','Questions'),
-- CTA EN
('cta.badge','en','Secured by DannyChain Layer 2 × Bitget Wallet'),('cta.title1','en','Start Mining'),('cta.title2','en','HMOOB'),('cta.titleEnd','en','Today'),('cta.desc','en','Join 3,300+ miners already earning daily rewards with 365% annual ROI.'),('cta.steps','en','Download Bitget Wallet → Open hmoob.io in DApp browser → Connect wallet → Choose a Boost → Start mining immediately.'),('cta.launchApp','en','Launch Mining App'),('cta.tradeDex','en','Trade on DanDEX'),('cta.exploreScan','en','Explore DanScan'),('cta.downloadWallet','en','Download a Compatible Wallet'),('cta.getWallet','en','Get Bitget Wallet'),('cta.trust1','en','Self-custodial security'),('cta.trust2','en','No hardware needed'),('cta.trust3','en','On-chain transparency'),
-- Footer EN
('footer.desc','en','Cloud-based HMOOB mining on DannyChain Layer 2. Empowering the Hmong community through accessible Web3 technology.'),('footer.online','en','Platform Online'),('footer.platform','en','Platform'),('footer.launchApp','en','Launch App ↗'),('footer.ecosystem','en','Ecosystem'),('footer.contactUs','en','Contact Us'),('footer.whatsapp','en','Chat on WhatsApp'),('footer.facebook','en','Follow on Facebook'),('footer.copyright','en','Built on DannyChain Layer 2. All rights reserved.'),

-- Navbar HMN
('nav.about','hmn','Hais Txog'),('nav.howItWorks','hmn','Ua Li Cas'),('nav.features','hmn','Cov Yam Ntxwv'),('nav.security','hmn','Kev Ruaj Ntseg'),('nav.boostPlans','hmn','Boost Plans'),('nav.ecosystem','hmn','Ecosystem'),('nav.faq','hmn','Nqe Lus Nug'),('nav.getStarted','hmn','Pib Tam Sim'),
-- Hero HMN
('hero.live','hmn','Khawb Tam Sim — 3,310+ Cov Neeg Khawb'),('hero.badge','hmn','Tsim Rau DannyChain × Bitget Wallet'),('hero.title1','hmn','Khawb'),('hero.title2','hmn','HMOOB'),('hero.title3','hmn','Khwv Txhua Hnub.'),('hero.desc','hmn','Txuas los ntawm Bitget Wallet, nce koj tus hash rate, thiab khawb HMOOB tokens — tsis xav tau kho vajtse. Khwv tau'),('hero.roi','hmn','365% ROI'),('hero.descEnd','hmn','hauv 365 hnub ntawm DannyChain ecosystem.'),('hero.startMining','hmn','Pib Khawb'),('hero.downloadWallet','hmn','Download Bitget Wallet'),('hero.annualRoi','hmn','365% ROI Ib Xyoos'),('hero.noHardware','hmn','Tsis Xav Tau Kho Vajtse'),('hero.selfCustodial','hmn','Self-Custodial Wallet'),
-- Trust HMN
('trust.poweredBy','hmn','Siv & Sib Txuas Nrog'),
-- About HMN
('about.label','hmn','Hais Txog HMOOB Mining'),('about.title1','hmn','Haiv'),('about.title2','hmn','Hmoob Tus'),('about.titleEnd','hmn','Crypto Token'),('about.p1','hmn','HMOOB Mining yog ib lub platform khawb crypto hauv huab cua tsim rau ntawm DannyChain Layer 2 blockchain. Cov neeg siv txuas los ntawm'),('about.bitget','hmn','Bitget Wallet'),('about.p1End','hmn','app — ib lub Web3 wallet uas muaj 80M+ cov neeg siv — los khawb HMOOB tokens los ntawm kev yuav boost plans thiab khwv tau rewards txhua hnub, tsis xav tau kho vajtse.'),('about.p2','hmn','Ib feem ntawm ib lub ecosystem uas loj tuaj suav nrog DannyChain (Layer 2 blockchain), DanDEX (kev sib pauv crypto), DanMarket (khw muag khoom digital), thiab DanScan (blockchain explorer) — HMOOB Mining sawv cev rau haiv Hmoob txoj kev nkag mus rau Web3 nrog ib lub platform tsim rau kev yooj yim.'),
-- AppPreview HMN
('appPreview.label','hmn','Mobile-First Platform'),('appPreview.title1','hmn','Khawb Qhov Twg,'),('appPreview.title2','hmn','Thaum Twg Los Tau'),('appPreview.desc','hmn','HMOOB Mining ua hauj lwm zoo los ntawm'),('appPreview.descEnd','hmn','app — ib lub Web3 wallet uas muaj 80M+ cov neeg siv thoob ntiaj teb. Qhib hmoob.io hauv wallet lub DApp browser los nkag tag nrho cov features.'),('appPreview.desc2','hmn','Bitget Wallet muaj self-custodial kev ruaj ntseg, multi-chain support, thiab DApp browser — ua rau nws yog txoj kev zoo tshaj plaws mus rau HMOOB Mining thiab DannyChain ecosystem.'),('appPreview.openApp','hmn','Qhib HMOOB Mining'),('appPreview.getWallet','hmn','Tau Bitget Wallet'),('appPreview.hmoobDesc','hmn','Khawb hauv huab cua — nce hash rate, khwv HMOOB rewards txhua hnub'),('appPreview.dandexDesc','hmn','Kev sib pauv crypto — swap tokens, muab liquidity, saib charts'),('appPreview.danscanDesc','hmn','Blockchain explorer — nrhiav transactions, blocks, wallets & gas'),('appPreview.compatibleWallets','hmn','Cov Wallet Sib Haum'),
-- HowItWorks HMN
('howItWorks.label','hmn','Ua Li Cas'),('howItWorks.title1','hmn','Plaub Kauj Ruam Los'),('howItWorks.title2','hmn','Khawb HMOOB'),('howItWorks.cta','hmn','Tau ntawm Google Play'),('howItWorks.wallet','hmn','Bitget Wallet'),
-- Features HMN
('features.label','hmn','Cov Yam Ntxwv'),('features.title1','hmn','Txhua Yam Hauv'),('features.title2','hmn','Ib Lub Platform'),('features.desc','hmn','Khawb, khwv, pauv, thiab loj hlob koj cov HMOOB'),
-- Security HMN
('security.label','hmn','Kev Ruaj Ntseg & Kev Ntseeg Siab'),('security.title1','hmn','Koj Cov Khoom,'),('security.title2','hmn','Koj Tswj'),('security.desc','hmn','Tsim nrog kev ruaj ntseg zoo tshaj plaws — vim kev ntseeg siab tau los ntawm kev ua, tsis yog kev xav'),('security.verify','hmn','Txheeb ntawm DanScan Explorer ↗'),
-- Boost HMN
('boost.label','hmn','Mining Boosts'),('boost.title1','hmn','Nce Koj Lub'),('boost.title2','hmn','Zog Khawb'),('boost.desc','hmn','Nce koj tus hash rate thiab khwv tau ntau HMOOB nrog peb cov boost plans'),('boost.recommended','hmn','Pom Zoo'),('boost.suffix','hmn','Boost'),('boost.hashRate','hmn','Hash Rate'),('boost.miningPower','hmn','Zog Khawb'),('boost.totalReturn','hmn','Tag Nrho Rov Qab'),('boost.duration','hmn','Sij Hawm'),('boost.days','hmn','365 hnub'),('boost.getBoost','hmn','Tau Boost'),
-- Ecosystem HMN
('ecosystem.label','hmn','Ecosystem'),('ecosystem.title1','hmn','Lub'),('ecosystem.title2','hmn','DannyChain'),('ecosystem.titleEnd','hmn','Ecosystem'),('ecosystem.desc','hmn','HMOOB Mining yog ib feem ntawm tag nrho blockchain ecosystem — los ntawm Layer 2 infrastructure mus rau decentralized trading'),
-- EcosystemFlow HMN
('flow.label','hmn','Txuas Li Cas'),('flow.title1','hmn','Ib Lub Ecosystem,'),('flow.title2','hmn','Peb Lub Platform'),('flow.titleEnd','hmn',''),('flow.desc','hmn','Download ib lub wallet, txuas rau DannyChain, thiab nkag mus rau tag nrho ecosystem — khawb, pauv, thiab tshawb nrhiav hauv ib qho chaw'),('flow.step1Title','hmn','Tau Ib Lub Wallet'),('flow.step1Desc','hmn','Download ib lub Web3 wallet uas muaj DApp browser'),('flow.step2Title','hmn','Txuas Rau DannyChain'),('flow.step2Desc','hmn','Qhib platform URL hauv wallet lub DApp browser'),('flow.step3Title','hmn','Nkag Mus Rau Ecosystem'),('flow.step3Desc','hmn','Khawb HMOOB, pauv ntawm DanDEX, los sis tshawb ntawm DanScan'),('flow.miningDesc','hmn','Khawb hauv huab cua — khwv HMOOB rewards txhua hnub nrog 365% ROI'),('flow.dexDesc','hmn','Kev sib pauv crypto — swap tokens thiab muab liquidity'),('flow.scanDesc','hmn','Blockchain explorer — nrhiav transactions, blocks, thiab wallets'),
-- Vision HMN
('vision.label','hmn','Peb Lub Zeem Muag'),('vision.quote','hmn','"HMOOB Mining tsis yog ib lub platform xwb — nws yog peb haiv neeg txoj kev nkag mus rau lub neej yav tom ntej decentralized. Tsim rau ntawm DannyChain, peb tsim ib lub ecosystem tag nrho uas haiv Hmoob thiab txhua tus neeg siv tuaj yeem khawb, khwv, pauv, thiab loj hlob ua ke."'),('vision.team','hmn','HMOOB Pab Neeg'),('vision.role','hmn','Cov Tsim & Cov Ua'),('vision.roadmapTitle1','hmn','Peb Txoj'),('vision.roadmapTitle2','hmn','Kev Npaj'),('vision.now','hmn','TAM SIM'),
-- Video HMN
('video.label','hmn','Saib'),('video.title1','hmn','Saib'),('video.title2','hmn','Hmoob.io'),('video.titleEnd','hmn','Ua Hauj Lwm Li Cas'),('video.desc','hmn','Kawm txog peb lub zeem muag thiab kev khawb crypto hauv huab cua uas ua rau kev khwv nyiaj crypto yooj yim rau txhua tus'),
-- Testimonials HMN
('testimonials.label','hmn','Zej Zog'),('testimonials.title1','hmn','Cov Neeg Khawb'),('testimonials.title2','hmn','Hais Li Cas'),('testimonials.desc','hmn','Cov lus tseeb los ntawm cov tswv cuab hauv zej zog'),('testimonials.verified','hmn','Txheeb Lawm'),('testimonials.hashRate','hmn','Hash Rate'),('testimonials.boost','hmn','Boost'),
-- FAQ HMN
('faq.label','hmn','Nqe Lus Nug'),('faq.title1','hmn','Cov Lus Nug'),('faq.title2','hmn','Nquag Nug'),
-- CTA HMN
('cta.badge','hmn','Ruaj Ntseg Los Ntawm DannyChain Layer 2 × Bitget Wallet'),('cta.title1','hmn','Pib Khawb'),('cta.title2','hmn','HMOOB'),('cta.titleEnd','hmn','Hnub No'),('cta.desc','hmn','Koom nrog 3,300+ cov neeg khawb uas twb khwv tau rewards txhua hnub nrog 365% ROI ib xyoos.'),('cta.steps','hmn','Download Bitget Wallet → Qhib hmoob.io hauv DApp browser → Txuas wallet → Xaiv Boost → Pib khawb tam sim ntawd.'),('cta.launchApp','hmn','Qhib Mining App'),('cta.tradeDex','hmn','Pauv ntawm DanDEX'),('cta.exploreScan','hmn','Tshawb DanScan'),('cta.downloadWallet','hmn','Download Ib Lub Wallet'),('cta.getWallet','hmn','Tau Bitget Wallet'),('cta.trust1','hmn','Self-custodial kev ruaj ntseg'),('cta.trust2','hmn','Tsis xav tau kho vajtse'),('cta.trust3','hmn','On-chain pom tseeb'),
-- Footer HMN
('footer.desc','hmn','Khawb HMOOB hauv huab cua ntawm DannyChain Layer 2. Pab haiv Hmoob los ntawm Web3 technology.'),('footer.online','hmn','Platform Online'),('footer.platform','hmn','Platform'),('footer.launchApp','hmn','Qhib App ↗'),('footer.ecosystem','hmn','Ecosystem'),('footer.contactUs','hmn','Hu Rau Peb'),('footer.whatsapp','hmn','Chat ntawm WhatsApp'),('footer.facebook','hmn','Follow ntawm Facebook'),('footer.copyright','hmn','Tsim rau DannyChain Layer 2. Txhua txoj cai reserved.');
